---
title: "Field Temp Data"
author: "Sara Michele Schaal"
date: "3/15/2018"
output: html_document
---

```{r, warning = FALSE}
knitr::opts_knit$set(root.dir = "/Users/saraschaal/Documents/Northeastern/LotterhosLab/Research/Field Work/2015/TPC_Experiment/Analysis")
```

#Aphrodite Point Data
##Monthly Average SST
```{r}
# Load Libraries
  library(ggplot2)
  library(scales)
  library(dplyr)


# Read in data and Manipulate Data
  aphmonthSST <- read.csv(  "./data/2004_2011MonthSSTAphroditePoint.csv")
  aphmonthSST.long <- reshape(aphmonthSST, varying = list(2:13), idvar = "year", direction = "long")
  colnames(aphmonthSST.long) <- c("year", "month", "SST")

# Plot Monthly Averages
  aphmonthSSTplot <- ggplot(data=aphmonthSST.long, 
                           aes(x=month, y=SST, 
                              group=as.factor(year), 
                              color = as.integer(year)))  +
                   geom_point() + 
                   geom_smooth(method = "loess", se = FALSE) 
  aphmonthSSTplot + labs(y = "Monthly Average SST", x = "Month") + ggtitle("Aphrodite Point") 

# box plot of Monthly Average SST at Aphrodite Point
  boxplot(SST~year, data = aphmonthSST.long, ylim = c(6,15), 
          ylab = "Monthly Mean SST", xlab = "Year")
  
# Extract recruitment months
  recruitmonths <- aphmonthSST.long[aphmonthSST.long$month == 5 | 
                                    aphmonthSST.long$month == 6 | 
                                    aphmonthSST.long$month == 7 | 
                                    aphmonthSST.long$month == 8, ]
  recruitmonths <- subset(recruitmonths, subset = recruitmonths$year > 2003 & recruitmonths$year < 2016)
# boxplot recruitment months
  boxplot(SST~year, data = recruitmonths, 
          ylab = "Monthly Mean SST", xlab = "Year")
  
  
```


##Monthly Max?
```{r}
# Input data
  aphdailySST <- read.csv("./data/AmphitriteDailySalTemp.csv")

# Manipulate Data
  aphdaily2004 <- subset(aphdailySST, subset = aphdailySST$Year > 2003 & aphdailySST$Year < 2016)
  aphdaily2004 <- aphdaily2004[aphdaily2004$Temperature < 99.9,]
  aphdaily2004$MonthDay <- paste(aphdaily2004$Month, aphdaily2004$Day)
  aphdaily2004$YMD <- paste(aphdaily2004$Year, aphdaily2004$Month, aphdaily2004$Day)
  aphdaily2004$Date <- as.Date(aphdaily2004$YMD, "%Y %m %d")

# Set standard error function
  SE <- function(x){
    sd(x)/sqrt(length(x))
  }
  
# Get monthly max temperature
  month.max <- aggregate(Temperature ~ Year + Month, data = aphdaily2004, FUN = max)
  month.max$YearMonth <- paste(month.max$Year, month.max$Month, "01", sep = "-")
  month.max$Date <- as.Date(month.max$YearMonth, "%Y-%m-%d")
  month.max <- month.max[order(month.max$Date),]

# Get monthly mean with CIs  
  month.mean <- aggregate(Temperature ~ Year + Month, data = aphdaily2004, FUN = mean)
  month.mean$YearMonth <- paste(month.mean$Year, month.mean$Month, "01", sep = "-")
  month.mean$Date <- as.Date(month.mean$YearMonth, "%Y-%m-%d")
  month.mean <- month.mean[order(month.mean$Date),]
  
  month.mean$SE <- aggregate(Temperature ~ Year + Month, data = aphdaily2004, FUN = SE)
  month.mean$upr <- month.mean$SE + month.mean$Temperature
  month.mean$low <- month.mean$Temperature - month.mean$SE
  
# Plot Monthly Max
  aphdailySSTplot <- ggplot(data=month.max, 
                         aes(x=Month, y=Temperature, 
                            group=as.factor(Year), 
                            color = as.integer(Year)))  +
                 geom_point() + 
                 geom_smooth(method = "loess", se = FALSE) 
                 
aphdailySSTplot + labs(y = "Daily SST", x = "Day") + ggtitle("Aphrodite Point") 


dev.off()
# boxplot
boxplot(Temperature~Year, data = month.max, 
        ylab = "Monthly Max SST", xlab = "Year")


recruitmonths.daily <- month.max[month.max$Month == 5 |
                           month.max$Month == 6 | 
                           month.max$Month == 7,]
boxplot(Temperature~Year, data = recruitmonths.daily, 
        ylab = "Monthly Max SST", xlab = "Year")
plot(Temperature~Date, data = aphdaily2004, type = "l")
```

#two panel plot
```{r}
par(mfrow = c(1,2))

boxplot(SST~year, data = recruitmonths, 
          ylab = "Monthly Mean SST", xlab = "Year")

boxplot(Temperature~Year, data = recruitmonths.daily, 
        ylab = "Monthly Max SST", xlab = "Year")
mtext("Aphrodite Point Mean and Max Monthly SST/n for Recruitment Months (May, June & July)", side = 3, outer = TRUE, cex = 1.3)

par(mfrow = c(1,2))
plot(Temperature~Date, data = month.max, ylim = c(7, 17), type = "l", main = "Monthly Max Temperature")
plot(Temperature~Date, data = month.mean, type = "l", ylim = c(7,17), main = "Monthly Mean Temperature")

```


##Katie's Data
### six sampling sites
```{r}
## Import data
  tempSampSitesOrg <- read.csv("./data/TempData_site_Species.csv")

## Subsetting 
  # for columns of interest
  tempSampSitesOrg <- subset(tempSampSitesOrg, select = c(ActualDate, Site, Temperature))
  # Subset for only those values over 0 (zeros added when temperatures weren't taken)
  tempSampSitesNoZeros <- tempSampSitesOrg[tempSampSitesOrg$Temperature > 0,]
  # Remove rows with any NAs
  tempSampSites <- na.omit(tempSampSitesNoZeros)
   
## Data manipulation 
  # Convert date column to date format and extract year for new column
  tempSampSites$Date <- as.Date(tempSampSites$ActualDate, "%m/%d/%Y")
  tempSampSites$Year <- substring(as.character(tempSampSites$Date),1,4)
  tempSampSites$Month <- as.numeric(substring(as.character(tempSampSites$Date),6,7))
  
  # Convert number months to names
  tempSampSites$MonthName <- NA
  for(i in 1:nrow(tempSampSites)){
    if(tempSampSites$Month[i] == 6){
      tempSampSites$MonthName[i] <- "June"
    } else if(tempSampSites$Month[i] == 7){
      tempSampSites$MonthName[i] <- "July"
    } else if(tempSampSites$Month[i] == 8){
      tempSampSites$MonthName[i] <- "August"
    } else if(tempSampSites$Month[i] == 5){
      tempSampSites$MonthName[i] <- "May"
    } else {
      tempSampSites$MonthName[i] <- NA
    }
  }
  
  # Convert data into the same scale some years Fahrenheit was taken others Celcius
  for(i in 1:nrow(tempSampSites)){
    if(tempSampSites$Temperature[i] > 40){
      tempSampSites$Temperature[i] <- (tempSampSites$Temperature[i]-32)*(5/9)
    } else {
      tempSampSites$Temperature[i] <- tempSampSites$Temperature[i]
    }
  } 
  
  # Subset the data for only sites I sampled
  tempSampSixSites <- tempSampSites[tempSampSites$Site == "Bluestone" |
                                         tempSampSites$Site == "Blowhole" |
                                         tempSampSites$Site == "Execution" |
                                         tempSampSites$Site == "Nudibranch" |
                                         tempSampSites$Site == "Prasiola", ]
# Set standard error function
  SE <- function(x){
    sd(x)/sqrt(length(x))
  }
  
  meanTempKaties <- aggregate(Temperature~Month+Year, data = tempSampSixSites, FUN = mean)
  confidMeanTempKaties <- aggregate(Temperature~Month+Year, data = tempSampSixSites, FUN = SE)
  meanTempKaties$upp <- meanTempKaties$Temperature + 1.96*confidMeanTempKaties$Temperature
  meanTempKaties$lowr <- meanTempKaties$Temperature - 1.96*confidMeanTempKaties$Temperature
  maxTempKaties <- aggregate(Temperature~Date, data = tempSampSixSites, FUN = max)
 
## Plotting

  par(mfrow = c(2,2))
  par(oma = c(4, 4, 2, 1))
  par(mar = c(2, 2, 1, 1))
  tempSampSixSites$Year <- as.factor(tempSampSixSites$Year)
  boxplot(Temperature~Year, data = tempSampSixSites[tempSampSixSites$Month == 5,], 
          ylim = c(10, 21))
  text(1, 20, label = "May", cex = 1.5)
  boxplot(Temperature~Year, data = tempSampSixSites[tempSampSixSites$Month == 6,], 
          ylim = c(10, 21))
  text(1.1, 20, label = "June", cex = 1.5)
  boxplot(Temperature~Year, data = tempSampSixSites[tempSampSixSites$Month == 7,], 
          ylim = c(10, 21))
  text(1.1, 20, label = "July", cex = 1.5)
  boxplot(Temperature~Year, data = tempSampSixSites[tempSampSixSites$Month == 8,],
          ylim = c(10, 21))
  text(1.4, 20, label = "August", cex = 1.5)
  mtext("Year", side = 1, outer = TRUE, cex = 1.2, line = 2.2)
  mtext("Temperature", side = 2, outer = TRUE, cex = 1.2, line = 2.2)
  
  
  mtext("Data from 6 Sampling Sites", side = 3, outer = TRUE, cex = 1.4)
  
# Mean of recruitment months
  boxplot(Temperature~Year, data = tempSampSixSites, ylim = c(10,21))
  zeros.data <- data.frame(ActualDate = c(2004, 2005, 2011, 2012, 2013), Site = "Blowhole", 
             Temperature = NA, Date = c(2004-06-08, 2005-06-08, 2011-06-08, 2012-06-08, 2013-06-08),
             Year = c(2004, 2005, 2011, 2012, 2013), Month = 6, MonthName = "June", stringsAsFactors = FALSE)
  tempSampSixSites$ActualDate <- as.character(tempSampSixSites$ActualDate)
  tempSampSixSites$Date <- as.character(tempSampSixSites$Date)
  tempSampSixSites$Year <- as.numeric(as.character(tempSampSixSites$Year))
  tempSampSixSitesAll <- rbind(tempSampSixSites, zeros.data)
  tempSampSixSitesAll$Year <- as.factor(tempSampSixSitesAll$Year)
  
  boxplot(Temperature~Year, data = tempSampSixSitesAll)
  temp.model <- lm(Temperature~Year, data = tempSampSixSitesAll)
  summary(aov(temp.model))
  plot(temp.model)
  shapiro.test(temp.model$residuals) #0.03  just barely sig 
```


```{r}

#########################################
#### Two Panel AphPoint & Samp Sites ####
#########################################
par(mfrow = c(1,2))
boxplot(SST~year, data = recruitmonths, 
          ylab = expression(paste('Mean SST (',degree,'C)',sep='')), xlab = "Year", col = "cornflowerblue",
        ylim = c(10,20))
boxplot(Temperature~Year, data = tempSampSixSitesAll, col = "aquamarine",
        ylab = "", ylim = c(10, 20))

dev.off()
#####################
#### Single Plot ####
#####################
sites.df <- tempSampSixSitesAll[,c(3,5,6)]
aph.df <- recruitmonths[,c(1:3)]
sites.df$location <- "SampSites"
aph.df$location <- "Aphrodite Point"
colnames(sites.df) <- c("SST", "year", "month", "location")
df.locs <- rbind(sites.df, aph.df)
df.locs <- na.omit(df.locs, cols = year)
par(mfrow = c(1,1))
boxplot(SST~location+year, data = df.locs, at = c(1:2, 4:5, 7:8, 10:11, 13:14, 16:17, 19:20, 22:23, 25:26, 28:29, 31:32, 34:35), col = c("cornflowerblue", "aquamarine" ), names = c("      2004", "", "     2005", "", "      2006", "", "      2007", "", "      2008", "", "      2009", "", "      2010", "", "       2011", "", "      2012", "", "      2013", "", "      2014", "", "      2015", ""), ylab = expression(paste('Sea Surface Temperature (',degree,'C)',sep='')), xlab = "Year", las = 2)
legend("topleft", legend = c("Aphrodite Point", "Six Sampling Locations"), fill = c("cornflowerblue", "aquamarine"), cex = 0.8)


```


## Analysis
```{r}
library(car)
modfieldTemp <- lm(SST~location, data = df.locs)
summary(aov(modfieldTemp))
summary(modfieldTemp)
Anova(modfieldTemp, type = 2)
shapiro.test(modfieldTemp$residuals) # normal

## overall quantiles, min & max of sampling locations
quantile(df.locs[df.locs$location == "SampSites", 1])
min(df.locs[df.locs$location == "SampSites",1])
max(df.locs[df.locs$location == "SampSites",1])

## quantiles in 2010
quantile(df.locs[df.locs$location == "SampSites" & df.locs$year == 2010, 1])
min(df.locs[df.locs$location == "SampSites" & df.locs$year == 2010, 1])
max(df.locs[df.locs$location == "SampSites" & df.locs$year == 2010, 1])

# overall min and max of sampling sites without year 2010
min(df.locs[df.locs$location == "SampSites" & df.locs$year != 2010, 1])
max(df.locs[df.locs$location == "SampSites" & df.locs$year != 2010, 1])

```