---
title: "Rockfish Temperature Data"
author: "Sara Michele Schaal"
date: "1/20/2019"
output: html_document
---

```{r}

# Install packages
    if(!("plyr" %in% installed.packages())){
      install.packages("plyr")
    }
    if(!("dplyr" %in% installed.packages())){
      install.packages("dplyr")
    }
    if(!("reshape2" %in% installed.packages())){
      install.packages("reshape2")
    }
    if(!("AICcmodavg" %in% installed.packages())){
      install.packages("AICcmodavg")
    }
    if(!("ggplot2" %in% installed.packages())){
      install.packages("ggplot2")
    }
    if(!("gridExtra" %in% installed.packages())){
      install.packages("gridExtra")
    }

    library(plyr)
    library(dplyr)
    library(reshape2)
    library(AICcmodavg)
    library(ggplot2)
    library(gridExtra)

```

```{r}
####################
#### BY Complex ####
####################
 # Load Data Frames
  temp.data <- read.csv("data/Temp_Data_Black.csv")
  head(temp.data)
  temp.data2 <- temp.data[, -(14:15)]
      
 # average temperatures measured by GAMMA and pH Meter and put values in new column
  temp.data$meanTemp <- rowMeans(subset(temp.data, select = c(Gamma, pH_Meter)), 
                                     na.rm = TRUE)

 # Separate temperature data with experiment buckets in one and holding tanks in the other
  df.expBuckets <-  temp.data[temp.data$Bucket_ID != "BIG 1" | temp.data$Bucket_ID != "BIG 2" | 
                              temp.data$Bucket_ID != "BIG 3" | temp.data$Bucket_ID != "COLD" | 
                              temp.data$Bucket_ID != "HOT" | temp.data$Bucket_ID != "SW1" | 
                              temp.data$Bucket_ID != "SW2", ]
  df.holdBuckets <- temp.data[temp.data$Bucket_ID == "BIG 1" | 
                              temp.data$Bucket_ID == "BIG 2" | 
                              temp.data$Bucket_ID == "BIG 3",]

 # Turn data frame into tlb_df object so that text wraps so they don't fill screen
  temp.df <- tbl_df(temp.data2)
  levels(temp.df$Bucket_ID)
      
 # get mean and standard deviation of bucket temps
  summary.data <- select(temp.data, Bucket_ID, Temperature_Treatment, meanTemp)
  melted.temp.data <- melt(summary.data, id.vars = c("Bucket_ID", "Temperature_Treatment"), 
                           na.rm = TRUE)
  summary.stats.black <- ddply(melted.temp.data, c("Bucket_ID", "Temperature_Treatment"), 
                               summarise, mean = mean(value), sd = sd(value))
  melted.treat.data <- melted.temp.data[!(melted.temp.data$Bucket_ID == "COLD" |
                                          melted.temp.data$Bucket_ID == "HOT" |
                                          melted.temp.data$Bucket_ID == "SW1" |
                                          melted.temp.data$Bucket_ID == "SW2" |
                                          melted.temp.data$Bucket_ID == "BIG 1" | 
                                          melted.temp.data$Bucket_ID == "BIG 2" |
                                          melted.temp.data$Bucket_ID == "BIG 3" ),]
  
  summary.stats.blk.treat <- ddply(melted.treat.data, c("Bucket_ID","Temperature_Treatment"), 
                                summarise, mean = mean(value), sd = sd(value))

  treatment.buckets.summ.blk <- summary.stats.black[c(1:5, 7, 9, 10:16), ]
  all.treatment.buckets.blk <- summary.stats.black[c(1:16),]
  write.csv(all.treatment.buckets.blk, "data/black_exp_temps.csv", row.names = FALSE)
      
####################      
#### CQ Complex ####
####################
 # Load Data
  temp.data.cp <- read.csv("data/Temp_Data_Copper.csv")
  head(temp.data.cp)

 # Turn data fram into a tbl_df to wrap text and calculate Mean of Gamma and pH Meter temps
  temp.df.cp <- tbl_df(temp.data.cp)
  temp.df.cp$mean <- rowMeans(subset(temp.df.cp, select = c(Gamma, pH_Meter)), 
                                  na.rm = TRUE)

 # Calculate summary statistics
  summary.data.cp <- select(temp.df.cp, Bucket_ID, Temperature_Treatment, mean)
  melted.temp.data.cp <- melt(summary.data.cp, id.vars = c("Bucket_ID", "Temperature_Treatment"), 
                                  na.rm = TRUE)
  melted.treat.data.cp <- melted.temp.data.cp[!(melted.temp.data.cp$Bucket_ID == "COLD" |
                                                melted.temp.data.cp$Bucket_ID == "HOT" |
                                                melted.temp.data.cp$Bucket_ID == "SW1" |
                                                melted.temp.data.cp$Bucket_ID == "SW2" |
                                                melted.temp.data.cp$Bucket_ID == "BIG 1" | 
                                                melted.temp.data.cp$Bucket_ID == "BIG 2" |
                                                melted.temp.data.cp$Bucket_ID == "BIG 3" ),]
  
  summary.stats.copper <- ddply(melted.temp.data.cp, c("Bucket_ID","Temperature_Treatment"), 
                                summarise, mean = mean(value), sd = sd(value))
  summary.stats.copper.treat <- ddply(melted.treat.data.cp, c("Bucket_ID","Temperature_Treatment"), 
                                summarise, mean = mean(value), sd = sd(value))
  
 # Separate out just treatment values
  treatment.buckets.summ.cp <- summary.stats.copper[c(1:6, 9:16), ]
  all.treatment.buckets.cp <- summary.stats.copper[c(1:16),]
  write.csv(all.treatment.buckets.cp, "data/copper_exp_temps.csv", row.names = FALSE)

  # Reorder data to be in numerical ascending order 
  # **(only way for loop to work properly)
  summary.stats.blk.treat$Bucket_ID <- as.numeric(as.character(summary.stats.blk.treat$Bucket_ID))
  summary.stats.copper.treat$Bucket_ID <- as.numeric(as.character(summary.stats.copper.treat$Bucket_ID))
  black.temps.asc <-  summary.stats.blk.treat[order(summary.stats.blk.treat$Bucket_ID), ]
  copper.temps.asc <- summary.stats.copper.treat[order(summary.stats.copper.treat$Bucket_ID), ]
  
  melted.treat.data$ExpTemp <- NULL
  melted.treat.data.cp$ExpTemp <- NULL
  # Fill in actual mean temperature data from experiment
  # BY complex
  for(i in 1:16){
    for(j in 1:nrow(melted.treat.data)){
      if(melted.treat.data$Bucket_ID[j] == i){
       melted.treat.data$ExpTemp[j] <- black.temps.asc$mean[i]
      }
    }
  }
  
  # CQ complex
  for(i in 1:16){
    for(j in 1:nrow(melted.treat.data.cp)){
      if(melted.treat.data.cp$Bucket_ID[j] == i){
        melted.treat.data.cp$ExpTemp[j] <- copper.temps.asc$mean[i]
      }
    }
  }
  
# Combine dataframes for a master dataset
  melted.treat.data$Species <- "BY Complex"
  melted.treat.data.cp$Species <- "CQ Complex"
  all.melted.data <- rbind(melted.treat.data, melted.treat.data.cp)
  all.melted.data$Species <- as.factor(all.melted.data$Species)
  melted.treat.data$RTemperature <- round(melted.treat.data$ExpTemp, 1)
  melted.treat.data.cp$RTemperature <- round(melted.treat.data.cp$ExpTemp, 1)

```


```{r}
######################################
### Boxplot of Bucket Temperatures ###
######################################
  par(mfrow = c(1,2))
  par(oma = c(4, 4, 1, 1))
  par(mar = c(2, 2, 2, 1))
  bp <- boxplot(value~RTemperature, data = melted.treat.data, ylim = c(8,24))
  text(12, 9, labels = "BY Complex Experiment")
  mtext(text = "A", side = 3, adj = 0.01, padj = 0.01)
  boxplot(value~RTemperature, data = melted.treat.data.cp, col = "orange", ylim = c(8,24))
  text(12, 9, labels = "CQ Complex Experiment")
  mtext(text = "B", side = 3, adj = 0.01, padj = 0.01)
  mtext(side = 2, outer = TRUE, cex = 1, line = 2.2, 
        text = expression(paste('Temperature Across Experiment (',degree,'C)',sep='')))
  mtext(side = 1, outer = TRUE, cex = 1, line = 2.2,
        text = expression(paste('Treatment Temperature (',degree,'C)',sep='')))
  
##################################
#### Plot on Continuous Scale ####
##################################
  
  by.exp.temp <-  ggplot(melted.treat.data, aes(x=ExpTemp, y=value)) +
                         geom_boxplot(fill="white", aes(group = cut_width(ExpTemp, 0.05))) + 
                         theme(panel.grid.major = element_blank(), 
                               panel.grid.minor = element_blank(),
                               panel.background = element_blank(), 
                               axis.line = element_line(colour = "black")) + 
                         xlab(expression(paste('Treatment Temperature (',degree,'C)', sep=""))) + 
                         ylab(expression(paste('Mean Temperature (',degree,'C)', sep=""))) + 
                         annotate(geom="text", x=20, y=11, label="BY Complex",
                                  color="black")

  cp.exp.temp <- ggplot(melted.treat.data.cp, aes(x=ExpTemp, y=value)) +
                        geom_boxplot(fill="orange", aes(group = cut_width(ExpTemp, 0.05))) + 
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(),
                              panel.background = element_blank(), 
                              axis.line = element_line(colour = "black")) +
                        xlab(expression(paste('Treatment Temperature (',degree,'C)', sep=""))) +
                        ylab(NULL) +
                        annotate(geom="text", x=20, y=11, label="CQ Complex",
                                 color="black")
  grid.arrange(by.exp.temp, cp.exp.temp, nrow = 1)

#####################
#### Single Plot ####
#####################
  ### Does not look good
  all.exp.temp <- ggplot(all.melted.data, aes(x=ExpTemp, y=value, colour = Species)) +
                        geom_boxplot(aes(group = cut_width(ExpTemp, 0.05))) + 
                        scale_fill_manual(breaks = c("BY Complex", "CQ Complex"), 
                                          values = c("white", "orange")) +
                        theme(panel.grid.major = element_blank(), 
                              panel.grid.minor = element_blank(),
                              panel.background = element_blank(), 
                              axis.line = element_line(colour = "black")) +
                        xlab(expression(paste('Treatment Temperature (',degree,'C)', sep=""))) +
                        ylab(NULL) +
                        annotate(geom="text", x=20, y=11, label="CQ Complex",
                                 color="black")
  
```
