---
title: "Growth Rate Analysis"
author: Sara Michele Schaal
output: pdf_document
---

```{r}
# Load Packages
    library("plyr")
    library("dplyr")
    library("reshape2")
    library("ggplot2")
    library("AICcmodavg")

# Load Data Frame
df.blacktemp <- read.csv("Temp_Data_Black.csv")
df.coppertemp <- read.csv("Temp_Data_Copper.csv")
df.growth <- read.csv("Fish_Measurement_Data_w_IDs.csv")

# Subset Dataframe to Include only Those Necessary for Analysis
df.subgrowth  <- subset(df.growth, select = c("Date", "Died_0_Lived_1", "Length_mm", 
                                              "Weight_g","Experimental_Treatment_C", "Bucket" ))

# Remove columns with any NAs
df.completegrowth <- na.omit(df.subgrowth)

df.completegrowth$exp.temp <- c(rep(10.51111, 12), rep(10.58704, 8), rep(13.46111, 12), 
                                rep(13.71667, 12), rep(15.10000, 12), rep(17.15000, 4), 
                                rep(17.97037, 16), rep(19.22222, 12), rep(18.90926, 8), 
                                rep(19.98889, 4), rep(19.91852, 4), rep(21.03333, 8),
                                rep(21.40741, 4), rep(22.01296, 8))

```

```{r}

## Length Data ##
   # Get measurement data from first day and last day of experiment
      correct.day.cp <- which(df.completegrowth$Date==20150704)
      start.length.cp <- tapply(df.completegrowth$Length_mm[correct.day.cp], 
                                df.completegrowth$exp.temp[correct.day.cp],mean)
      last.day.cp <- which(df.completegrowth$Date==20150718)
      end.length.cp <- tapply(df.completegrowth$Length_mm[last.day.cp], 
                              df.completegrowth$exp.temp[last.day.cp], mean, na.rm=TRUE)

    # Create data frames for starting data and ending data and merge them
      df.start.length.cp <- data.frame(bucket=names(start.length.cp), start.length.cp)
      df.end.length.cp <- data.frame(bucket=names(end.length.cp), end.length.cp)
      df.length.cp <- merge(df.start.length.cp, df.end.length.cp)

    # Add in temperature data
    #  df.length.cp$exp.temp <- c(10.51111, 19.98889, 19.91852, 21.03333, 21.40741, 22.01296, 
                          #       10.58704, 13.46111, 13.71667, 15.10000, 17.15000, 17.97037, 
                          #       19.22222, 18.90926)

## Growth Data ##
# Get weight data from first day and last day of experiment
      start.weight.cp <- tapply(df.completegrowth$Weight_g[correct.day.cp], 
                                df.completegrowth$exp.temp[correct.day.cp], mean)
      end.weight.cp <- tapply(df.completegrowth$Weight_g[last.day.cp], 
                              df.completegrowth$exp.temp[last.day.cp], mean, na.rm=TRUE)

    # Create data frames for starting data and ending data and merge them
      df.start.weight.cp <- data.frame(bucket=names(start.weight.cp), start.weight.cp)
      df.end.weight.cp <- data.frame(bucket=names(end.weight.cp), end.weight.cp)
      df.weight.cp <- merge(df.start.weight.cp, df.end.weight.cp)
   

## Combined Data ##
  # Combine Length and Weight data
    df.growth.cp <- merge(df.length.cp, df.weight.cp)

```

```{r}

### Calculate Growth Statistics ###
 
  ## Condition Factor ##

    # start and end condition factor calculation
      df.growth.cp$CF.start <- ((df.growth.cp$start.weight.cp)/(df.growth.cp$start.length.cp)^3)*100
      df.growth.cp$CF.end <- ((df.growth.cp$end.weight.cp)/(df.growth.cp$end.length.cp)^3)*100

    # Change in CF
      df.growth.cp$CF.change <- (df.growth.cp$CF.end-df.growth.cp$CF.start)

  ## % Weight Gain ##

    df.growth.cp$weight.change <- (df.growth.cp$end.weight.cp-df.growth.cp$start.weight.cp) 
    df.growth.cp$percent.weight <- ((df.growth.cp$weight.change/df.growth.cp$start.weight.cp)*100)

# as.numeric
df.growth.cp$exp.temp <- as.numeric(paste(df.growth.cp$bucket))

```

```{r}

### Plots ###

  # Scatterplot 
  plot(df.growth.cp$exp.temp, df.growth.cp$CF.change, pch = 18,
           bty = "l", main = "Condition Factor - Copper Rockfish",
           ylab = "Condition Factor", 
           xlab = "Temperature Treatment (Celcius)", col = "blue")

  abline(lm(df.growth.cp$CF.change~df.growth.cp$exp.temp), col = "blue")

  # General Additive Model (GAM)
  ggplot(df.growth.cp, aes(x=exp.temp, y=CF.change)) + labs(x = "Temperature (Celcius)", 
            y = "Condition Factor") + ggtitle("Condition Factor - Copper Rockfish") + geom_point() + geom_smooth()

  # Scatterplot
  plot(df.growth.cp$exp.temp, df.growth.cp$percent.weight, pch = 18, bty = "l",
        main = "% Weight Change - Copper Rockfish", ylab = "% Weight Change", 
        xlab = "Temperature Treatment (Celcius)", col = "blue")

  abline(lm(df.growth.cp$percent.weight~df.growth.cp$exp.temp), col = "blue")

with(df.growth.cp, scatter.smooth(percent.weight ~ exp.temp))
  # General Additive Model (GAM)
  ggplot(df.growth.cp, aes(x=exp.temp, y=percent.weight)) + labs(x = "Temperature (Celcius)", 
            y = "% Weight Change") + ggtitle("% Weight Change - Copper Rockfish") + geom_point() + geom_smooth()

```

```{r}

### Analysis ###

# Condition Factor #
  full.cp.CF <- lm(df.growth.cp$CF.change~df.growth.cp$exp.temp + I(df.growth.cp$exp.temp^2)
                     + df.growth.cp$start.weight.cp)
  summary(full.cp.CF)
  drop1(full.cp.CF)
  

  # Drop start.weight
     drop.start.cp.CF <- lm(df.growth.cp$CF.change~df.growth.cp$exp.temp + I(df.growth.cp$exp.temp^2))
                       
    summary(drop.start.cp.CF)
    drop1(drop.start.cp.CF)

  # Drop squared term
    drop.square.cp.CF <- lm(df.growth.cp$CF.change~df.growth.cp$exp.temp)
    summary(drop.square.cp.CF)


# Marginally significant 0.08919.

# % Weight Gain #
  full.cp.perc <- lm(df.growth.cp$percent.weight~df.growth.cp$exp.temp
                     + df.growth.cp$start.weight.cp)
  summary(full.cp.perc)
  drop1(full.cp.perc)

# WOOOOOOOT significant.


```

## Black Rockfish

```{r}

    # Subset Dataframe to Include only Those Necessary for Analysis
      df.subgrowth.blk  <- subset(df.growth, select = c("Date", "Length_mm", 
                                              "Weight_g","Experimental_Treatment_C", 
                                              "Bucket" ))

      df.growth.2<- na.omit(df.subgrowth.blk)
      

## Length Data ##
    # Get measurement data from first day and last day of experiment
      correct.day.blk <- which(df.growth.2$Date==20150620)
      start.length.blk <- tapply(df.growth.2$Length_mm[correct.day.blk], 
                                 df.growth.2$Bucket[correct.day.blk], mean)
      last.day.blk <- which(df.growth.2$Date==20150703)
      end.length.blk <- tapply(df.growth.2$Length_mm[last.day.blk], 
                               df.growth.2$Bucket[last.day.blk], mean, na.rm=TRUE)

    # Create data frames for starting data and ending data and merge them
      df.start.length.blk <- data.frame(bucket=names(start.length.blk), start.length.blk)
      df.end.length.blk <- data.frame(bucket=names(end.length.blk), end.length.blk)
      df.length.blk <- merge(df.start.length.blk, df.end.length.blk)

    # Add in exp.temp
      df.length.blk$exp.temp <- c(10.45769, 19.45192, 20.18269, 
                                  20.71346, 20.97308, 22.61731, 
                                  10.33846, 13.46111, 13.89808, 
                                  15.23462, 17.86923, 19.35962, 
                                  18.48462, 19.98462)


   ## Weight Data ##

      start.weight.blk <- tapply(df.growth.2$Weight_g[correct.day.blk], 
                                 df.growth.2$Bucket[correct.day.blk], mean)
      end.weight.blk <- tapply(df.growth.2$Weight_g[last.day.blk], 
                               df.growth.2$Bucket[last.day.blk], mean, na.rm=TRUE)

    # Create data frames for starting data and ending data and merge them
      df.start.weight.blk <- data.frame(bucket=names(start.weight.blk), start.weight.blk)
      df.end.weight.blk <- data.frame(bucket=names(end.weight.blk), end.weight.blk)
      df.weight.blk <- merge(df.start.weight.blk, df.end.weight.blk)

  ## Combine Data ##

    df.growth.blk <- merge(df.length.blk, df.weight.blk)    

```

```{r}

### Calculate Growth Statistics ###

## Condition Factor ##
      df.growth.blk$CF.start <- ((df.growth.blk$start.weight.blk)/(df.growth.blk$start.length.blk)^3)*100
      df.growth.blk$CF.end <- ((df.growth.blk$end.weight.blk)/(df.growth.blk$end.length.blk)^3)*100

    # Change in CF
      df.growth.blk$CF.change <- (df.growth.blk$CF.end-df.growth.blk$CF.start)

## % Weight Change ##

      df.growth.blk$weight.change <- (df.growth.blk$end.weight.blk-df.growth.blk$start.weight.blk)
      df.growth.blk$percent.weight <- ((df.growth.blk$weight.change/df.growth.blk$start.weight.blk)*100)


```

```{r}

### Plots ###
 plot(df.growth.blk$exp.temp, df.growth.blk$CF.change, pch = 20,
           bty = "l", main = "Condition Factor - Black Rockfish",
           ylab = "Condition Factor", 
           xlab = "Temperature Treatment (Celcius)")

  abline(lm(df.growth.blk$CF.change~df.growth.blk$exp.temp))

# General Additive Model (GAM)
  ggplot(df.growth.blk, aes(x=exp.temp, y=CF.change)) + labs(x = "Temperature (Celcius)", 
            y = "Condition Factor") + ggtitle("Condition Factor - Black Rockfish") + geom_point() + geom_smooth()

  # Scatterplot
  plot(df.growth.blk$exp.temp, df.growth.blk$percent.weight, pch = 20, bty = "l",
        main = "% Weight Change - Black Rockfish", ylab = "% Weight Change", 
        xlab = expression(paste("Temperature Treatment (",degree,"C)")), ylim = c(-25, 30))

  abline(lm(df.growth.blk$percent.weight~df.growth.blk$exp.temp))
  summary(lm(df.growth.blk$percent.weight~df.growth.blk$exp.temp))
  text(15, 20, labels = "slope = -1.46 (p = 0.00018)")
  

  plot(df.growth.cp$exp.temp, df.growth.cp$percent.weight, pch = 18, bty = "l", 
        col = "blue", main = "% Weight Change - Copper Rockfish", ylab = "% Weight Change", 
        xlab = expression(paste("Temperature Treatment (",degree,"C)")), ylim = c(-25, 30))

  abline(lm(df.growth.cp$percent.weight~df.growth.cp$exp.temp), col = "blue")
  summary(lm(df.growth.cp$percent.weight~df.growth.cp$exp.temp))  
  text (18, 20, labels = "slope = -2.64 (p = 0.0017)")

# General Additive Model (GAM)
  ggplot(df.growth.blk, aes(x=exp.temp, y=percent.weight)) + labs(x = "Temperature (Celcius)", 
            y = "% Weight Change") + ggtitle("% Weight Change - Black Rockfish") + geom_point() + geom_smooth()


```

```{r}
### Analysis ###

# Condition Factor #
  full.blk.CF <- lm(df.growth.blk$CF.change~df.growth.blk$exp.temp + I(df.growth.blk$exp.temp^2)
                     + df.growth.blk$start.weight.blk)
  summary(full.blk.CF)
  drop1(full.blk.CF)
  

  # Drop start.weight
    drop.start.blk.CF <- lm(df.growth.blk$CF.change~df.growth.blk$exp.temp + I(df.growth.blk$exp.temp^2))                     
    summary(drop.start.cp.CF)
    drop1(drop.start.cp.CF)
  # Best model but not significant

  # Drop squared term
    drop.square.blk.CF <- lm(df.growth.blk$CF.change~df.growth.blk$exp.temp)
    summary(drop.square.blk.CF)
  # Also not significant. 

# % Weight Gain #
  full.blk.perc <- lm(df.growth.blk$percent.weight~df.growth.blk$exp.temp + I(df.growth.blk$exp.temp^2)
                     + df.growth.blk$start.weight.blk)
  summary(full.blk.perc)
  drop1(full.blk.perc)

  # drop starting weight
    drop.start.blk.perc <- lm(df.growth.blk$percent.weight~df.growth.blk$exp.temp + 
                                I(df.growth.blk$exp.temp^2))
    summary(drop.start.blk.perc)
    drop1(drop.start.blk.perc)

  #drop linear
    drop.linear.blk.perc <- lm(df.growth.blk$percent.weight~I(df.growth.blk$exp.temp^2))
    summary(drop.linear.blk.perc)

  #highly significant squared term



```

```{r}

#mortality

df.growth <- read.csv("Fish_Measurement_Data_w_IDs.csv")

df.survival  <- subset(df.growth, select = c("Date", "Fish_ID_on_photo", "Species", "Days_Survived", "Length_mm", "Weight_g", "Experimental_Treatment_C", "Bucket", "Mort"))

df.survival <- na.omit(df.survival)

df.cp.survival <- df.survival[df.survival$Species == "Copper", ]

df.cp.survival$exp_temp <- c(rep(10.51111, 4), rep(10.58704, 3), rep(13.46111, 4), 
                                rep(13.71667, 4), rep(15.10000, 4), rep(17.15000, 4), 
                                rep(17.97037, 4), rep(19.22222, 4), rep(18.90926, 3), 
                                rep(19.98889, 4), rep(19.91852, 3), rep(21.03333, 4),
                                rep(21.40741, 4), rep(22.01296, 4), rep(22.01296, 4),
                                rep(22.41667, 3))

model1.cp  <- lm(df.cp.survival$Days_Survived~df.cp.survival$exp_temp + df.cp.survival$Length_mm)
summary(model1.cp)
drop1(model1.cp)

plot(df.cp.survival$Days_Survived~df.cp.survival$Length_mm)

df.blk.survival <- df.survival[df.survival$Date < 20150704,]

df.blk.survival$exp_temp <- c(rep(10.45769, 2), rep(10.33846, 3), rep(14.09038, 2), 
                              rep(13.89808, 2), rep(15.23462, 3), rep(17.86923, 3), 
                              rep(19.35962, 3), rep(18.48462, 3), rep(19.98462, 2), 
                              rep(19.45192, 3), rep(20.18269, 3), rep(20.71346, 3), 
                              rep(20.97308, 2), rep(21.86875, 2), rep(22.61731, 2), 
                              rep(22.35682, 3))  


model1.blk <- lm(df.blk.survival$Days_Survived~df.blk.survival$exp_temp + df.blk.survival$Length_mm)
summary(model1.blk)
drop1(model1.blk)


```