---
title: "Growth with Species ID"
author: "Sara M Schaal"
date: "May 2, 2016"
output: pdf_document
---


```{r}
df.species <- read.csv("Fish_Measurement_Data_w_IDs_seq_2.csv")

df.species.2 <- subset(df.species, select = c("Date", "Species_Seq","Individual_IDs", "Length_mm", "Weight_g", "Bucket"))

df.species.3 <- na.omit(df.species.2)

df.species.3 <- df.species.3[!(df.species.3$Species_Seq == "" | df.species.3$Species_Seq == "Dusky?"),]
df.species.blkexp <- df.species.3[which(df.species.3$Date == 20150620 | df.species.3$Date == 20150703), ]
df.species.blkexp <- df.species.blkexp[!(df.species.blkexp$Bucket == 14 | df.species.blkexp$Bucket == 16),]
df.species.cpexp  <- df.species.3[(df.species.3$Date == 20150704 | df.species.3$Date == 20150718),]


length.data.blk <- matrix(nrow = 28, ncol = 5, NA) 
colnames(length.data.blk) <- c("Species", "Individual_ID", "Length_Change", "Percent_Weight", "Bucket")

blkbuck1 <- df.species.blkexp[which(df.species.blkexp$Bucket == 1),]
length.data.blk[1,1] <- "Yellowtail" 
length.data.blk[1,2] <- 2
length.data.blk[1,3] <- blkbuck1[2,4]-blkbuck1[1,4]
length.data.blk[1,4] <- (((blkbuck1[2,5]-blkbuck1[1,5])/blkbuck1[1,5])*100)
length.data.blk[1,5] <- 10.45769

blkbuck2 <- df.species.blkexp[which(df.species.blkexp$Bucket == 2),]
length.data.blk[2,1] <- "Black" 
length.data.blk[2,2] <- 1
length.data.blk[2,3] <- blkbuck2[2,4]-blkbuck2[1,4]
length.data.blk[2,4] <- (((blkbuck2[2,5]-blkbuck2[1,5])/blkbuck2[1,5])*100)
length.data.blk[2,5] <- 10.33846

blkbuck3 <- df.species.blkexp[which(df.species.blkexp$Bucket == 3),]
length.data.blk[3,1] <- "Black" 
length.data.blk[3,2] <- 1
length.data.blk[3,3] <- blkbuck3[3,4]-blkbuck3[1,4]
length.data.blk[3,4] <- (((blkbuck3[3,5]-blkbuck3[1,5])/blkbuck3[1,5])*100)
length.data.blk[3,5] <- 14.09038
length.data.blk[4,1] <- "Black" 
length.data.blk[4,2] <- 2
length.data.blk[4,3] <- blkbuck3[4,4]-blkbuck3[2,4]
length.data.blk[4,4] <- (((blkbuck3[4,5]-blkbuck3[2,5])/blkbuck3[2,5])*100)
length.data.blk[4,5] <- 14.09038

blkbuck4 <- df.species.blkexp[which(df.species.blkexp$Bucket == 4),]
length.data.blk[5,1] <- "Black" 
length.data.blk[5,2] <- 1
length.data.blk[5,3] <- blkbuck4[2,4]-blkbuck4[1,4]
length.data.blk[5,4] <- (((blkbuck4[2,5]-blkbuck4[1,5])/blkbuck4[1,5])*100)
length.data.blk[5,5] <- 13.89808

blkbuck5 <- df.species.blkexp[which(df.species.blkexp$Bucket == 5),]
length.data.blk[6,1] <- "Yellowtail" 
length.data.blk[6,2] <- 1
length.data.blk[6,3] <- blkbuck5[4,4]-blkbuck5[1,4]
length.data.blk[6,4] <- (((blkbuck5[4,5]-blkbuck5[1,5])/blkbuck5[1,5])*100)
length.data.blk[6,5] <- 15.23462
length.data.blk[7,1] <- "Black" 
length.data.blk[7,2] <- 2
length.data.blk[7,3] <- blkbuck5[6,4]-blkbuck5[2,4]
length.data.blk[7,4] <- (((blkbuck5[6,5]-blkbuck5[2,5])/blkbuck5[2,5])*100)
length.data.blk[7,5] <- 15.23462
length.data.blk[8,1] <- "Black" 
length.data.blk[8,2] <- 3
length.data.blk[8,3] <- blkbuck5[5,4]-blkbuck5[3,4]
length.data.blk[8,4] <- (((blkbuck5[5,5]-blkbuck5[3,5])/blkbuck5[3,5])*100)
length.data.blk[8,5] <- 15.23462

blkbuck6 <- df.species.blkexp[which(df.species.blkexp$Bucket == 6),]
length.data.blk[9,1] <- "Yellowtail" 
length.data.blk[9,2] <- 3
length.data.blk[9,3] <- blkbuck6[4,4]-blkbuck6[1,4]
length.data.blk[9,4] <- (((blkbuck6[4,5]-blkbuck6[1,5])/blkbuck6[1,5])*100)
length.data.blk[9,5] <- 17.86923
length.data.blk[10,1] <- "Yellowtail" 
length.data.blk[10,2] <- 2
length.data.blk[10,3] <- blkbuck6[3,4]-blkbuck6[2,4]
length.data.blk[10,4] <- (((blkbuck6[3,5]-blkbuck6[2,5])/blkbuck6[2,5])*100)
length.data.blk[10,5] <- 17.86923

blkbuck7 <- df.species.blkexp[which(df.species.blkexp$Bucket == 7),]
length.data.blk[11,1] <- "Yellowtail" 
length.data.blk[11,2] <- 2
length.data.blk[11,3] <- blkbuck7[4,4]-blkbuck7[1,4]
length.data.blk[11,4] <- (((blkbuck7[4,5]-blkbuck7[1,5])/blkbuck7[1,5])*100)
length.data.blk[11,5] <- 19.35962
length.data.blk[12,1] <- "Black" 
length.data.blk[12,2] <- 3
length.data.blk[12,3] <- blkbuck7[3,4]-blkbuck7[2,4]
length.data.blk[12,4] <- (((blkbuck7[3,5]-blkbuck7[2,5])/blkbuck7[2,5])*100)
length.data.blk[12,5] <- 19.35962

blkbuck8 <- df.species.blkexp[which(df.species.blkexp$Bucket == 8),]
length.data.blk[13,1] <- "Black" 
length.data.blk[13,2] <- 1
length.data.blk[13,3] <- blkbuck8[4,4]-blkbuck8[1,4]
length.data.blk[13,4] <- (((blkbuck8[4,5]-blkbuck8[1,5])/blkbuck8[1,5])*100)
length.data.blk[13,5] <- 18.48462
length.data.blk[14,1] <- "Yellowtail" 
length.data.blk[14,2] <- 2
length.data.blk[14,3] <- blkbuck8[3,4]-blkbuck8[2,4]
length.data.blk[14,4] <- (((blkbuck8[3,5]-blkbuck8[2,5])/blkbuck8[2,5])*100)
length.data.blk[14,5] <- 18.48462

blkbuck9 <- df.species.blkexp[which(df.species.blkexp$Bucket == 9),]
length.data.blk[15,1] <- "Black" 
length.data.blk[15,2] <- 1
length.data.blk[15,3] <- blkbuck9[3,4]-blkbuck9[1,4]
length.data.blk[15,4] <- (((blkbuck9[3,5]-blkbuck9[1,5])/blkbuck9[1,5])*100)
length.data.blk[15,5] <- 19.98462
length.data.blk[16,1] <- "Yellowtail" 
length.data.blk[16,2] <- 2
length.data.blk[16,3] <- blkbuck9[4,4]-blkbuck9[2,4]
length.data.blk[16,4] <- (((blkbuck9[4,5]-blkbuck9[2,5])/blkbuck9[2,5])*100)
length.data.blk[16,5] <- 19.98462

blkbuck10 <- df.species.blkexp[which(df.species.blkexp$Bucket == 10),]
length.data.blk[17,1] <- "Black" 
length.data.blk[17,2] <- 1
length.data.blk[17,3] <- blkbuck10[5,4]-blkbuck10[1,4]
length.data.blk[17,4] <- (((blkbuck10[5,5]-blkbuck10[1,5])/blkbuck10[1,5])*100)
length.data.blk[17,5] <- 19.45192
length.data.blk[18,1] <- "Black" 
length.data.blk[18,2] <- 3
length.data.blk[18,3] <- blkbuck10[4,4]-blkbuck10[2,4]
length.data.blk[18,4] <- (((blkbuck10[4,5]-blkbuck10[2,5])/blkbuck10[2,5])*100)
length.data.blk[18,5] <- 19.45192
length.data.blk[19,1] <- "Black" 
length.data.blk[19,2] <- 2
length.data.blk[19,3] <- blkbuck10[6,4]-blkbuck10[3,4]
length.data.blk[19,4] <- (((blkbuck10[6,5]-blkbuck10[3,5])/blkbuck10[3,5])*100)
length.data.blk[19,5] <- 19.45192

blkbuck11 <- df.species.blkexp[which(df.species.blkexp$Bucket == 11),]
length.data.blk[20,1] <- "Black/Yellowtail" 
length.data.blk[20,2] <- 2
length.data.blk[20,3] <- blkbuck11[4,4]-blkbuck11[1,4]
length.data.blk[20,4] <- (((blkbuck11[4,5]-blkbuck11[1,5])/blkbuck11[1,5])*100)
length.data.blk[20,5] <- 20.18269
length.data.blk[21,1] <- "Black" 
length.data.blk[21,2] <- 1
length.data.blk[21,3] <- blkbuck11[5,4]-blkbuck11[2,4]
length.data.blk[21,4] <- (((blkbuck11[5,5]-blkbuck11[2,5])/blkbuck11[2,5])*100)
length.data.blk[21,5] <- 20.18269
length.data.blk[22,1] <- "Black" 
length.data.blk[22,2] <- 3
length.data.blk[22,3] <- blkbuck11[6,4]-blkbuck11[3,4]
length.data.blk[22,4] <- (((blkbuck11[6,5]-blkbuck11[3,5])/blkbuck11[3,5])*100)
length.data.blk[22,5] <- 20.18269

blkbuck12 <- df.species.blkexp[which(df.species.blkexp$Bucket == 12),]
length.data.blk[23,1] <- "Black" 
length.data.blk[23,2] <- 1
length.data.blk[23,3] <- blkbuck12[6,4]-blkbuck12[1,4]
length.data.blk[23,4] <- (((blkbuck12[6,5]-blkbuck12[1,5])/blkbuck12[1,5])*100)
length.data.blk[23,5] <- 20.71346
length.data.blk[24,1] <- "Black" 
length.data.blk[24,2] <- 2
length.data.blk[24,3] <- blkbuck12[5,4]-blkbuck12[2,4]
length.data.blk[24,4] <- (((blkbuck12[5,5]-blkbuck12[2,5])/blkbuck12[2,5])*100)
length.data.blk[24,5] <- 20.71346
length.data.blk[25,1] <- "Black/Yellowtail" 
length.data.blk[25,2] <- 3
length.data.blk[25,3] <- blkbuck12[4,4]-blkbuck12[3,4]
length.data.blk[25,4] <- (((blkbuck12[4,5]-blkbuck12[3,5])/blkbuck12[3,5])*100)
length.data.blk[25,5] <- 20.71346

blkbuck13 <- df.species.blkexp[which(df.species.blkexp$Bucket == 13),]
length.data.blk[26,1] <- "Black" 
length.data.blk[26,2] <- 1
length.data.blk[26,3] <- blkbuck13[4,4]-blkbuck13[1,4]
length.data.blk[26,4] <- (((blkbuck13[4,5]-blkbuck13[1,5])/blkbuck13[1,5])*100)
length.data.blk[26,5] <- 20.97308
length.data.blk[27,1] <- "Black" 
length.data.blk[27,2] <- 2
length.data.blk[27,3] <- blkbuck13[3,4]-blkbuck13[2,4]
length.data.blk[27,4] <- (((blkbuck13[3,5]-blkbuck13[2,5])/blkbuck13[2,5])*100)
length.data.blk[27,5] <- 20.97308

blkbuck15 <- df.species.blkexp[which(df.species.blkexp$Bucket == 15),]
length.data.blk[28,1] <- "Black" 
length.data.blk[28,2] <- 2
length.data.blk[28,3] <- blkbuck15[2,4]-blkbuck15[1,4]
length.data.blk[28,4] <- (((blkbuck15[2,5]-blkbuck15[1,5])/blkbuck15[1,5])*100)
length.data.blk[28,5] <- 22.61731

length.data.blk <- as.data.frame(length.data.blk)
length.data.blk$Percent_Weight <- (as.numeric(as.character(length.data.blk$Percent_Weight)))
length.data.blk$Bucket <- (as.numeric(as.character(length.data.blk$Bucket)))
length.data.blk$Length_Change <- (as.numeric(as.character(length.data.blk$Length_Change)))


length.data.black <- subset(length.data.blk, Species == "Black")
length.data.yellowtail <- subset(length.data.blk, Species == "Yellowtail")
length.data.y_b <- subset(length.data.blk, Species == "Black/Yellowtail")
```

Models Plotting

```{r}
mod1.growth.blk <- lm(length.data.black$Percent_Weight~length.data.black$Bucket)
summary(mod1.growth.blk)

mod1.growth.yt <- lm(length.data.yellowtail$Percent_Weight~length.data.yellowtail$Bucket)
summary(mod1.growth.yt)

plot(length.data.black$Bucket, length.data.black$Percent_Weight, pch = 20,
          bty = "l", main = "Percent Weight - Black",
          ylab = "Percent Weight Change", 
          xlab = "Experimental Temperature (Celcius)")

abline(mod1.growth.blk)

points(length.data.yellowtail$Bucket, length.data.yellowtail$Percent_Weight, pch = 15, col = "goldenrod")

abline(mod1.growth.yt, col = "goldenrod")

points(length.data.y_b$Bucket,length.data.y_b$Percent_Weight, pch = 17, col = "darkgray")

legend("topright", legend = c("Black", "Yellowtail", "Hybrid"), pch = c(20,15,17), col = c("black", "goldenrod", "darkgrey"))

```

Copper Analysis

```{r}
length.data.cp <- matrix(nrow = 28, ncol = 5, NA) 
colnames(length.data.cp) <- c("Species", "Individual_ID", "Length_Change", "Percent_Weight", "Bucket")

cpbuck1 <- df.species.cpexp[which(df.species.cpexp$Bucket == 1),]
cpbuck1 <- cpbuck1[!(cpbuck1$Individual_IDs == 1),]
length.data.cp[1,1] <- "Copper" 
length.data.cp[1,2] <- 3
length.data.cp[1,3] <- cpbuck1[5,4]-cpbuck1[1,4]
length.data.cp[1,4] <- (((cpbuck1[5,5]-cpbuck1[1,5])/cpbuck1[1,5])*100)
length.data.cp[1,5] <- 10.51111
length.data.cp[2,1] <- "Quillback" 
length.data.cp[2,2] <- 2
length.data.cp[2,3] <- cpbuck1[6,4]-cpbuck1[2,4]
length.data.cp[2,4] <- (((cpbuck1[6,5]-cpbuck1[2,5])/cpbuck1[2,5])*100)
length.data.cp[2,5] <- 10.51111
length.data.cp[3,1] <- "Copper" 
length.data.cp[3,2] <- 4
length.data.cp[3,3] <- cpbuck1[4,4]-cpbuck1[3,4]
length.data.cp[3,4] <- (((cpbuck1[4,5]-cpbuck1[3,5])/cpbuck1[3,5])*100)
length.data.cp[3,5] <- 10.51111

cpbuck2 <- df.species.cpexp[which(df.species.cpexp$Bucket == 2),]
cpbuck2 <- cpbuck2[!(cpbuck2$Individual_IDs == 2),]
length.data.cp[4,1] <- "Copper" 
length.data.cp[4,2] <- 1
length.data.cp[4,3] <- cpbuck2[2,4]-cpbuck2[1,4]
length.data.cp[4,4] <- (((cpbuck2[2,5]-cpbuck2[1,5])/cpbuck2[1,5])*100)
length.data.cp[4,5] <- 10.58704

cpbuck3 <- df.species.cpexp[which(df.species.cpexp$Bucket == 3),]
cpbuck3 <- cpbuck3[!(cpbuck3$Individual_IDs == 1),]
length.data.cp[5,1] <- "Copper" 
length.data.cp[5,2] <- 2
length.data.cp[5,3] <- cpbuck3[2,4]-cpbuck3[1,4]
length.data.cp[5,4] <- (((cpbuck3[2,5]-cpbuck3[1,5])/cpbuck3[1,5])*100)
length.data.cp[5,5] <- 13.46111

cpbuck4 <- df.species.cpexp[which(df.species.cpexp$Bucket == 4),]
cpbuck4 <- cpbuck4[!(cpbuck4$Individual_IDs == 2),]
length.data.cp[6,1] <- "Copper" 
length.data.cp[6,2] <- 4
length.data.cp[6,3] <- cpbuck4[3,4]-cpbuck4[1,4]
length.data.cp[6,4] <- (((cpbuck4[3,5]-cpbuck4[1,5])/cpbuck4[1,5])*100)
length.data.cp[6,5] <- 13.71667 
length.data.cp[7,1] <- "Copper" 
length.data.cp[7,2] <- 1
length.data.cp[7,3] <- cpbuck4[4,4]-cpbuck4[2,4]
length.data.cp[7,4] <- (((cpbuck4[4,5]-cpbuck4[2,5])/cpbuck4[2,5])*100)
length.data.cp[7,5] <- 13.71667 

cpbuck5 <- df.species.cpexp[which(df.species.cpexp$Bucket == 5),]
length.data.cp[8,1] <- "Copper" 
length.data.cp[8,2] <- 1
length.data.cp[8,3] <- cpbuck5[5,4]-cpbuck5[1,4]
length.data.cp[8,4] <- (((cpbuck5[5,5]-cpbuck5[1,5])/cpbuck5[1,5])*100)
length.data.cp[8,5] <- 15.10000
length.data.cp[9,1] <- "Quillback" 
length.data.cp[9,2] <- 3
length.data.cp[9,3] <- cpbuck5[6,4]-cpbuck5[2,4]
length.data.cp[9,4] <- (((cpbuck5[6,5]-cpbuck5[2,5])/cpbuck5[2,5])*100)
length.data.cp[9,5] <- 15.10000
length.data.cp[10,1] <- "Quillback" 
length.data.cp[10,2] <- 2
length.data.cp[10,3] <- cpbuck5[4,4]-cpbuck5[3,4]
length.data.cp[10,4] <- (((cpbuck5[4,5]-cpbuck5[3,5])/cpbuck5[3,5])*100)
length.data.cp[10,5] <- 15.10000

cpbuck6 <- df.species.cpexp[which(df.species.cpexp$Bucket == 6),]
cpbuck6 <- cpbuck6[!(cpbuck6$Individual_IDs == 4),]
length.data.cp[11,1] <- "Copper" 
length.data.cp[11,2] <- 1
length.data.cp[11,3] <- cpbuck6[5,4]-cpbuck6[1,4]
length.data.cp[11,4] <- (((cpbuck6[5,5]-cpbuck6[1,5])/cpbuck6[1,5])*100)
length.data.cp[11,5] <- 17.15000
length.data.cp[12,1] <- "Quillback" 
length.data.cp[12,2] <- 2
length.data.cp[12,3] <- cpbuck6[6,4]-cpbuck6[2,4]
length.data.cp[12,4] <- (((cpbuck6[6,5]-cpbuck6[2,5])/cpbuck6[2,5])*100)
length.data.cp[12,5] <- 17.15000
length.data.cp[13,1] <- "Quillback" 
length.data.cp[13,2] <- 3
length.data.cp[13,3] <- cpbuck6[4,4]-cpbuck6[3,4]
length.data.cp[13,4] <- (((cpbuck6[4,5]-cpbuck6[3,5])/cpbuck6[3,5])*100)
length.data.cp[13,5] <- 17.15000

cpbuck7 <- df.species.cpexp[which(df.species.cpexp$Bucket == 7),]
length.data.cp[14,1] <- "Copper" 
length.data.cp[14,2] <- 3
length.data.cp[14,3] <- cpbuck7[5,4]-cpbuck7[1,4]
length.data.cp[14,4] <- (((cpbuck7[5,5]-cpbuck7[1,5])/cpbuck7[1,5])*100)
length.data.cp[14,5] <- 17.97037
length.data.cp[15,1] <- "Copper" 
length.data.cp[15,2] <- 4
length.data.cp[15,3] <- cpbuck7[6,4]-cpbuck7[2,4]
length.data.cp[15,4] <- (((cpbuck7[6,5]-cpbuck7[2,5])/cpbuck7[2,5])*100)
length.data.cp[15,5] <- 17.97037
length.data.cp[16,1] <- "Quillback" 
length.data.cp[16,2] <- 1
length.data.cp[16,3] <- cpbuck7[7,4]-cpbuck7[3,4]
length.data.cp[16,4] <- (((cpbuck7[7,5]-cpbuck7[3,5])/cpbuck7[3,5])*100)
length.data.cp[16,5] <- 17.97037
length.data.cp[17,1] <- "Copper" 
length.data.cp[17,2] <- 2
length.data.cp[17,3] <- cpbuck7[8,4]-cpbuck7[4,4]
length.data.cp[17,4] <- (((cpbuck7[8,5]-cpbuck7[4,5])/cpbuck7[4,5])*100)
length.data.cp[17,5] <- 17.97037

cpbuck8 <- df.species.cpexp[which(df.species.cpexp$Bucket == 8),]
cpbuck8 <- cpbuck8[!(cpbuck8$Individual_IDs == 2),]
length.data.cp[18,1] <- "Copper" 
length.data.cp[18,2] <- 4
length.data.cp[18,3] <- cpbuck8[4,4]-cpbuck8[1,4]
length.data.cp[18,4] <- (((cpbuck8[4,5]-cpbuck8[1,5])/cpbuck8[1,5])*100)
length.data.cp[18,5] <- 19.22222
length.data.cp[19,1] <- "Copper" 
length.data.cp[19,2] <- 3
length.data.cp[19,3] <- cpbuck8[6,4]-cpbuck8[2,4]
length.data.cp[19,4] <- (((cpbuck8[6,5]-cpbuck8[2,5])/cpbuck8[2,5])*100)
length.data.cp[19,5] <- 19.22222
length.data.cp[20,1] <- "Copper" 
length.data.cp[20,2] <- 1
length.data.cp[20,3] <- cpbuck8[5,4]-cpbuck8[3,4]
length.data.cp[20,4] <- (((cpbuck8[5,5]-cpbuck8[3,5])/cpbuck8[3,5])*100)
length.data.cp[20,5] <- 19.22222

cpbuck9 <- df.species.cpexp[which(df.species.cpexp$Bucket == 9),]
cpbuck9 <- cpbuck9[!(cpbuck9$Individual_IDs == 2),]
length.data.cp[21,1] <- "Copper" 
length.data.cp[21,2] <- 3
length.data.cp[21,3] <- cpbuck9[3,4]-cpbuck9[1,4]
length.data.cp[21,4] <- (((cpbuck9[3,5]-cpbuck9[1,5])/cpbuck9[1,5])*100)
length.data.cp[21,5] <- 18.90926
length.data.cp[22,1] <- "Copper" 
length.data.cp[22,2] <- 4
length.data.cp[22,3] <- cpbuck9[4,4]-cpbuck9[2,4]
length.data.cp[22,4] <- (((cpbuck9[4,5]-cpbuck9[2,5])/cpbuck9[2,5])*100)
length.data.cp[22,5] <- 18.90926

cpbuck10 <- df.species.cpexp[which(df.species.cpexp$Bucket == 10),]
cpbuck10 <- cpbuck10[!(cpbuck10$Individual_IDs == 2 | cpbuck10$Individual_IDs == 3 | cpbuck10$Individual_IDs == 4),]
length.data.cp[23,1] <- "Copper" 
length.data.cp[23,2] <- 1
length.data.cp[23,3] <- cpbuck10[2,4]-cpbuck10[1,4]
length.data.cp[23,4] <- (((cpbuck10[2,5]-cpbuck10[1,5])/cpbuck10[1,5])*100)
length.data.cp[23,5] <- 19.98889 

cpbuck11 <- df.species.cpexp[which(df.species.cpexp$Bucket == 11),]
length.data.cp[24,1] <- "Quillback" 
length.data.cp[24,2] <- 1
length.data.cp[24,3] <- cpbuck11[4,4]-cpbuck11[1,4]
length.data.cp[24,4] <- (((cpbuck11[4,5]-cpbuck11[1,5])/cpbuck11[1,5])*100)
length.data.cp[24,5] <- 19.91852
length.data.cp[25,1] <- "Copper" 
length.data.cp[25,2] <- 3
length.data.cp[25,3] <- cpbuck11[3,4]-cpbuck11[2,4]
length.data.cp[25,4] <- (((cpbuck11[3,5]-cpbuck11[2,5])/cpbuck11[2,5])*100)
length.data.cp[25,5] <- 19.91852

cpbuck13 <- df.species.cpexp[which(df.species.cpexp$Bucket == 13),]
cpbuck13 <- cpbuck13[!(cpbuck13$Individual_IDs == 3),]
length.data.cp[26,1] <- "Copper" 
length.data.cp[26,2] <- 2
length.data.cp[26,3] <- cpbuck13[2,4]-cpbuck13[1,4]
length.data.cp[26,4] <- (((cpbuck13[2,5]-cpbuck13[1,5])/cpbuck13[1,5])*100)
length.data.cp[26,5] <- 21.40741
                   
length.data.cp <- as.data.frame(length.data.cp)
length.data.cp$Percent_Weight <- (as.numeric(as.character(length.data.cp$Percent_Weight)))
length.data.cp$Bucket <- (as.numeric(as.character(length.data.cp$Bucket)))
length.data.cp$Length_Change <- (as.numeric(as.character(length.data.cp$Length_Change)))


length.data.copper <- subset(length.data.cp, Species == "Copper")
length.data.quillback <- subset(length.data.cp, Species == "Quillback")


par(mfrow=c(1,1))
plot(length.data.copper$Bucket, length.data.copper$Percent_Weight, pch = 20,
          bty = "l", main = "Percent Weight - Copper", type = "p",
          ylab = "Percent Weight Change", 
          xlab = "Experimental Temperature (Celcius)",
          col = "orange")

points(length.data.quillback$Bucket, length.data.quillback$Percent_Weight, pch = 15, col = "brown")
                      
legend("topright", legend = c("Copper", "Quillback"), pch = c(20,15), 
       col = c("orange", "brown")) 

curve(977.0086 - 197.9048*x + 13.1365*x^2 - 0.2886*x^3, add = T, col = "orange")
f2  <- function(x) (977.0086 - 197.9048*x + 13.1365*x^2 - 0.2886*x^3)
optimize(f2, c(10.51111, 22.85417), maximum = TRUE)
points(16.44927, -8.432869, col = "black", pch = "|")
text(13, 40, labels = expression(paste("T opt = 16.45",degree,"C")), col = "black")

mod1.growth.copper <- lm(length.data.copper$Percent_Weight~length.data.copper$Bucket + I(length.data.copper$Bucket^2) + I(length.data.copper$Bucket^3))
summary(mod1.growth.copper)
drop1(mod1.growth.copper)
#best model square and cubic significant

```

Old analysis

```{r}
df.quillback <- df.species.3[which(df.species.3$Species_Seq=="Quillback"),]
df.yellowtail <- df.species.3[which(df.species.3$Species_Seq=="Yellowtail"),]
df.copper <- df.species.3[which(df.species.3$Species_Seq=="Copper"),]
df.black <- df.species.3[which(df.species.3$Species_Seq=="Black"),]

all.species <- rbind(df.quillback,df.yellowtail,df.copper,df.black)
CQB <- rbind(df.quillback, df.copper)
BY <- rbind(df.black, df.yellowtail)

CQB$Species_Seq <- factor(CQB$Species_Seq)
BY$Species_Seq <- factor(BY$Species_Seq)
all.species$Species_Seq <- factor(all.species$Species_Seq)


#### BOXPLOTS ####
par(mfrow=c(1,2))
boxplot(Length_mm~Species_Seq, data = CQB, col = c("chocolate4", "darkorange1"), ylab = "Length_mm", main = "Species Lengths")
boxplot(Length_mm~Species_Seq, data = BY, col = c("azure4", "darkgoldenrod1"))

boxplot(Weight_g~Species_Seq, data = CQB, col = c("chocolate4", "darkorange1"), ylab = "Weight_g", main = "Species Weights")
boxplot(Weight_g~Species_Seq, data = BY, col = c("azure4", "darkgoldenrod1"))

#### SCATTER ####

CQB$Bucket[CQB$Bucket == 1]  <-  10.51111
CQB$Bucket[CQB$Bucket == 10]  <- 19.98889 
CQB$Bucket[CQB$Bucket == 11]  <- 19.91852
CQB$Bucket[CQB$Bucket == 12]  <- 21.03333
CQB$Bucket[CQB$Bucket == 13]  <- 21.40741 
CQB$Bucket[CQB$Bucket == 14]  <- 22.01296
CQB$Bucket[CQB$Bucket == 15]  <- 22.85417 
CQB$Bucket[CQB$Bucket == 16]  <- 22.41667
CQB$Bucket[CQB$Bucket == 2]  <- 10.58704 
CQB$Bucket[CQB$Bucket == 3]  <- 13.46111
CQB$Bucket[CQB$Bucket == 4]  <- 13.71667 
CQB$Bucket[CQB$Bucket == 5]  <- 15.10000
CQB$Bucket[CQB$Bucket == 6]  <- 17.15000
CQB$Bucket[CQB$Bucket == 7]  <- 17.97037 
CQB$Bucket[CQB$Bucket == 8]  <- 19.22222
CQB$Bucket[CQB$Bucket == 9]  <- 18.90926

  
plot(CQB$Length_mm~CQB$Bucket, col = c("darkorange1", "chocolate4")[CQB$Species_Seq], pch = 20, main = "Copper and Quillback", xlab = "Temperature", ylab = "Length")
plot(CQB$Weight_g~CQB$Bucket, col = c("darkorange1", "chocolate4")[CQB$Species_Seq], pch = 20, xlab = "Temperature", ylab = "Weight_g")

BY$Bucket[BY$Bucket == 1]  <-  10.45769 
BY$Bucket[BY$Bucket == 10]  <- 19.45192 
BY$Bucket[BY$Bucket == 11]  <- 20.18269
BY$Bucket[BY$Bucket == 12]  <- 20.71346 
BY$Bucket[BY$Bucket == 13]  <- 20.97308 
BY$Bucket[BY$Bucket == 14]  <- 21.86875
BY$Bucket[BY$Bucket == 15]  <- 22.61731 
BY$Bucket[BY$Bucket == 16]  <- 22.35682
BY$Bucket[BY$Bucket == 2]  <- 10.33846 
BY$Bucket[BY$Bucket == 3]  <- 14.09038
BY$Bucket[BY$Bucket == 4]  <- 13.89808 
BY$Bucket[BY$Bucket == 5]  <- 15.23462 
BY$Bucket[BY$Bucket == 6]  <- 17.86923
BY$Bucket[BY$Bucket == 7]  <- 19.35962 
BY$Bucket[BY$Bucket == 8]  <- 18.48462 
BY$Bucket[BY$Bucket == 9]  <- 19.98462

plot(BY$Length_mm~BY$Bucket, col = c("azure4", "darkgoldenrod1")[BY$Species_Seq], pch = 20, xlab = "Temperature", ylab = "Length", main = "Black and Yellowtail")
plot(BY$Weight_g~BY$Bucket, col = c("azure4", "darkgoldenrod1")[BY$Species_Seq], pch = 20, xlab = "Temperature", ylab = "Weight")

```
